
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace cfg
{
public partial class Tables
{
    public DataTable.CountryInfoTable CountryInfoTable {get; }
    public DataTable.LevelConfigTable LevelConfigTable {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        CountryInfoTable = new DataTable.CountryInfoTable(loader("datatable_countryinfotable"));
        LevelConfigTable = new DataTable.LevelConfigTable(loader("datatable_levelconfigtable"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        CountryInfoTable.ResolveRef(this);
        LevelConfigTable.ResolveRef(this);
    }
}

}

