
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.DataTable
{

public sealed partial class CountryInfo : Luban.BeanBase
{
    public CountryInfo(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Name = (string)_obj.GetValue("name");
        LocalName = (string)_obj.GetValue("local_name");
    }

    public static CountryInfo DeserializeCountryInfo(JToken _buf)
    {
        return new DataTable.CountryInfo(_buf);
    }

    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 本地化后名字
    /// </summary>
    public readonly string LocalName;


    public const int __ID__ = -268471174;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "name:" + Name + ","
        + "localName:" + LocalName + ","
        + "}";
    }
}
}

