
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.DataTable
{

public partial class CountryInfoTable
{
    private readonly System.Collections.Generic.Dictionary<string, DataTable.CountryInfo> _dataMap;
    private readonly System.Collections.Generic.List<DataTable.CountryInfo> _dataList;
    
    public CountryInfoTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, DataTable.CountryInfo>();
        _dataList = new System.Collections.Generic.List<DataTable.CountryInfo>();
        
        foreach(JObject _ele in _buf)
        {
            DataTable.CountryInfo _v;
            _v = DataTable.CountryInfo.DeserializeCountryInfo(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
         }
    }


    public System.Collections.Generic.Dictionary<string, DataTable.CountryInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<DataTable.CountryInfo> DataList => _dataList;

    public DataTable.CountryInfo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DataTable.CountryInfo Get(string key) => _dataMap[key];
    public DataTable.CountryInfo this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

