
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.DataTable
{

public sealed partial class LevelConfig : Luban.BeanBase
{
    public LevelConfig(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Column = (int)_obj.GetValue("column");
        Row = (int)_obj.GetValue("row");
        Seed = (int)_obj.GetValue("seed");
        Difficulty = (int)_obj.GetValue("difficulty");
        PosConfig = (string)_obj.GetValue("pos_config");
    }

    public static LevelConfig DeserializeLevelConfig(JToken _buf)
    {
        return new DataTable.LevelConfig(_buf);
    }

    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 列
    /// </summary>
    public readonly int Column;
    /// <summary>
    /// 行数
    /// </summary>
    public readonly int Row;
    /// <summary>
    /// 种子
    /// </summary>
    public readonly int Seed;
    /// <summary>
    /// 难度
    /// </summary>
    public readonly int Difficulty;
    /// <summary>
    /// 位置信息
    /// </summary>
    public readonly string PosConfig;


    public const int __ID__ = -1767680260;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "column:" + Column + ","
        + "row:" + Row + ","
        + "seed:" + Seed + ","
        + "difficulty:" + Difficulty + ","
        + "posConfig:" + PosConfig + ","
        + "}";
    }
}
}

