
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.DataTable
{

public partial class LevelConfigTable
{
    private readonly System.Collections.Generic.Dictionary<int, DataTable.LevelConfig> _dataMap;
    private readonly System.Collections.Generic.List<DataTable.LevelConfig> _dataList;
    
    public LevelConfigTable(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DataTable.LevelConfig>();
        _dataList = new System.Collections.Generic.List<DataTable.LevelConfig>();
        
        foreach(JObject _ele in _buf)
        {
            DataTable.LevelConfig _v;
            _v = DataTable.LevelConfig.DeserializeLevelConfig(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, DataTable.LevelConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<DataTable.LevelConfig> DataList => _dataList;

    public DataTable.LevelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DataTable.LevelConfig Get(int key) => _dataMap[key];
    public DataTable.LevelConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

